### ISSUE TITLE
Emacs sems to not have the correct flags

### ISSUE THREAD

**Issue by TheRealOne78** [szorfein/dots#11]
The issue #10 seems to be half resolved, because ``emerge`` is strugling with some flags issues:

```
emerge: there are no ebuilds built with USE flags to satisfy "app-emacs/emacs-common[games?,gui(-)?]".
!!! One of the following packages is required to complete your request:
- app-emacs/emacs-common-1.8::gentoo (Change USE: +gui)
- app-editors/emacs-27.2-r4::gentoo (Change USE: -gui)
(dependency required by "app-editors/emacs-27.2-r4::gentoo" [ebuild])
(dependency required by "emacs" [argument])
chezmoi: exit status 1
Beast-PC /etc/portage/package.use #
```

From what I can translate in that message, it seems like there is a missing dash in ``/etc/portage/package.use/emacs``:

```
Beast-PC ~ # cat /etc/portage/package.use/emacs
# doom-emacs need json
app-editors/emacs -alsa gui gtk json xft gpm

app-emacs/emacs-common -gui
Beast-PC ~ #
```

Replacing ``gui`` with ``-gui`` in ``app-editors/emacs -alsa gui gtk json xft gpm`` seems to solve the ermerge problem, however it needs to be updated in the chezmoi repo to be able to run the script without replacing again the ``-gui`` flag with ``gui``.

**Comment by Ariimeow78** [comment]
I made another issue because the issue #10 wasn't related direclty to ``chezmoi``.

**Comment by szorfein** [comment]
Thanks you to report theses issue :+1:

**Comment by Ariimeow78** [comment]
> Thanks you to report theses issue +1

No problem... I am just trying to make this for me in the first place and for others who want to use this amazing themes.

I found more issues, commited in a forked repo and found another one I can't solve https://github.com/szorfein/dots/pull/12 . I am horified to see how many issues a theme can have to be honest.

I will not close these issues yet, because the theme does not work yet.

**Comment by Ariimeow78** [comment]
this issue seems solved
