### ISSUE TITLE
Knock Knock

### ISSUE THREAD

**Issue by TheRealOne78** [szorfein/dots#14]
Who's there?
New.
New who?
New Issue!

I got this error:
![20211004_185750.jpg](https://user-images.githubusercontent.com/53640879/135885013-187c5fc4-75f1-4927-abb8-1e6b3ca886c0.jpg)

Ran ``chezmoi update`` again, gave me Brave browser emerge, emerge fine.
![20211004_185943.jpg](https://user-images.githubusercontent.com/53640879/135885209-914e98fc-9b5a-4527-929f-f449022f69a7.jpg)
except now there is a new error...

```
chezmoi: template: run_once90-stow.sh.tmpl:5:16 executing "run_once90-stow.sh.tmpl" at <.chezmoi.homedir>: map has no entry for key "homedir"
```

I am sorry for not giving a plain text and istead I am giving photos.. but GPM broke for some reason when I installed fresh gentoo. Will solve that problem later.

**Comment by Ariimeow78** [comment]
I mean...it kind of works but... not entirely... I can access all the themes except astronaut, it seems corupt, there were a few warnings/errors while installing the theme itself. But first of all I want to experiment first in a VM with gentoo. More information about what works and what doesn't work later.

**Comment by Ariimeow78** [comment]
![image](https://user-images.githubusercontent.com/53640879/139058224-69baaef2-7929-4b2c-86ac-103e4419d948.png)
Now it can't compile lightdm...
I have as well a stream on yt just in case... https://youtu.be/Jp_9xKOdpnI

**Comment by Ariimeow78** [comment]
oh I see now... It needs to be choosed one from systemd or elogind... since this theme uses systemd <i>in gentoo</i>, it needs to be set to systemd.

**Comment by szorfein** [comment]
I have added the use flag 'systemd' globally on my system, i know that a lot of people don't like this :)  
i would try to make this dependence optionnal in the next commit.

And about the theme astronaut, it's a theme not yet finish so it's normal that it does not work.

**Comment by Ariimeow78** [comment]
oh ok, I see.
