### ISSUE TITLE
error Removing old Stow links...

### ISSUE THREAD

**Issue by lloscarll** [szorfein/dots#17]
\033[0;96m-->\033[0;97m End for /tmp/1140284351.40-systemd-service.sh \033[0m
\033[0;96m--------------------------------------------------\033[0m
Removing old Stow links...
/tmp/2298139983.90-stow.sh: line 31: cd: /home/lloscarll/.dotfiles: No such file or directory
chezmoi: exit status 1

**Comment by szorfein** [comment]
I've renamed the script, try:

    chezmoi update
    chezmoi apply

**Comment by lloscarll** [comment]
ok thanks
