### ISSUE TITLE
Running this effectively kills new arch install

### ISSUE THREAD

**Issue by daciwolf** [szorfein/dots#18]
Ran all the instructions word for word, and what ended up happening was that I rebooted after applying and got a black screen with a cursor, I repeated this on 3 separate arch installs and they all ended up the exact same way. If you could shed some light on what is happening that would be awesome

**Comment by szorfein** [comment]
Hi, thanks for report.
There were some errors corrected, it should be fixed now (i've tested on Qemu).  
There is a long delay after [run_once_40-systemd-service.sh](https://github.com/szorfein/dots/blob/master/.chezmoiscripts/run_once_40-systemd-service.sh.tmpl) but no worry and wait :) it install all the content of [.chezmoiexternal.toml](https://github.com/szorfein/dots/blob/master/.chezmoiexternal.toml).
