### ISSUE TITLE
can't apply chezmoi

### ISSUE THREAD

**Issue by 0xSnoxzy** [szorfein/dots#19]
Hello, i'm new to arch and linux, i once installed some dots from another repository and applied them, now i want to apply and use this dots because i like them more, when doing "chezmoi apply" it looks for conflicting packages and it gives me this error:

looking for conflicting packages...
:: picom and picom-jonaburg-git are in conflict (compton). Remove picom-jonaburg-git? [y/N]
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependancies)
:: picom and picom-jonaburg-git are in conflict
chezmoi: exit status 1

Can you pls help me? I can't understand :(

**Comment by szorfein** [comment]
Hi, unfortunately, there is no automatic solution to resolve package conflicts with pacman.  
Here you have to manually remove `picom-jonaburg-git` and restart `chezmoi apply`

    sudo pacman -R picom-jonaburg-git
    chezmoi apply
