### ISSUE TITLE
chezmoi apply error

### ISSUE THREAD

**Issue by imskr** [szorfein/dots#3]
Its demanding github username and pass while running `chezmoi apply`

**Comment by imskr** [comment]
I just changed the config `themes=lines` 

Authentication failed for 'https://github.com/szorfein/lines.vim/'

**Comment by szorfein** [comment]
hmm, you don't need to fill `data.theme`, this variable is no more used,  

EDIT:
The value for github are used in: (`chezmoi cd && find . -type f | xargs grep .github.name`)
```
./.chezmoiignore:{{- if ne .github.name "szorfein" }}
./dot_gitconfig.tmpl:  name = {{ .github.name }}
./dot_gitconfig.tmpl:{{- if eq .github.name "szorfein" }}
./private_dot_gnupg/sshcontrol.tmpl:{{- if eq .github.name "szorfein" }}
./dot_weechat/private_irc.conf.tmpl:{{- if eq .github.name "szorfein" }}
./dot_weechat/private_irc.conf.tmpl:{{- if eq .github.name "szorfein" }}
./dot_weechat/private_irc.conf.tmpl:{{- if eq .github.name "szorfein" }}

```
It should not ask for passwork, maybe it related to your ~/.gitconfig. Try to modify data.github.name and data.github.email for see and make redo a `chezmoi apply`

chezmoi only ask for a mail address the first time.  
Else can you post the content of your `chezmoi edit-config` ? (without the value of your gpg key if any)

**Comment by imskr** [comment]
I was also trying another way given in wiki of dotfiles but `stow lines -t ~` don't work throws some error

**Comment by szorfein** [comment]
I've correct the wiki for the manual install.
