### ISSUE TITLE
Vim themes

### ISSUE THREAD

**Issue by pjhalsli** [szorfein/dots#5]
I use neovim - but assume that doesn't really matter?
I always just copied vim colors to their right place - but doing so with vamp and sci none of the themes work - I get tons of errors. so trying colorscheme sci for example gives me many errors - at the end of those the them looks like it's working just fine. Kinda curiosu why this happens?

**Comment by szorfein** [comment]
vamp, sci and probably others futur themes are based on the vim dracula, you can follow their installation, just replace the keyword dracula and the url.  
https://draculatheme.com/vim
