### ISSUE TITLE
GPG Decryption failed

### ISSUE THREAD

**Issue by stelgenhof** [szorfein/dots#6]
Thanks for the great dotfiles setup! Wanted to give it a try however after telling chezmoi to apply the changes, I got this message:
```
gpg: decryption failed: No secret key
```
I have added my GPG details in the chezmoi config file. However not sure I understand what GPG needs to decrypt. Is there some decrypted file somewhere?

Cheers! Sacha

**Comment by szorfein** [comment]
yeah, it's a painful problem. A temporary solution for now is to delete 2 files:

    $ chezmoi cd
    $ git rm private_dot_ssh/encrypted_private_gem-private_key.pem
    $ git rm private_dot_ssh/encrypted_private_gem-public_cert.pem

And commit the change to avoid the keys back on next update

    $ git commit -m "remove secret"

**Comment by stelgenhof** [comment]
Thanks for the quick response! That did the trick. Installation completed successfully.

Looks like some of the functions/menus don't work when I click on the various icons. For example switching to a different theme doesn't do anything. Perhaps because I am trying it in a VM or some other issue. I'll have a look to see what the issue may be.
