### ISSUE TITLE
Chezmoi failing to apply Dots

### ISSUE THREAD

**Issue by ghost** [szorfein/dots#7]
So I kinda having trouble when doing chezmoi apply

What should I do?

![image](https://user-images.githubusercontent.com/40330128/102486901-6af7b480-4072-11eb-83f4-a0f7be74182e.png)

**Comment by JC488** [comment]
I'm running Debian 10 if that helps

**Comment by JC488** [comment]
https://sharethe.minecraftdoublesmoothstoneslab.website/i/i36x.png

Also my chezmoi config

**Comment by JC488** [comment]
![image](https://user-images.githubusercontent.com/40330128/103052047-d379f080-45a0-11eb-8d1c-da0516817fb9.png)

Hey there, the installation going just fine, errors do appear

**Comment by szorfein** [comment]
Issue fixed with the #122eee0, thank you for report !
