### ISSUE TITLE
Please help! Chezmoi: exit status 1

### ISSUE THREAD

**Issue by Jabir-Srj** [szorfein/dots#9]
I can't figure out what is happening, I am using Arch Linux with xfce4.
Also I'm new to Linux if you don't mind :p

[I] ➜ chezmoi apply
.dmrc has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip
,quit]? skip
Removing old Stow links...
BUG in find_stowed_path? Absolute/relative mismatch between Stow dir .dotfiles and path /home/fattiejb/.local/share/chezmoi/asound/dot_asoundrc_pulse at /usr/share/perl5/vendor_perl/Stow.pm line 966, <DATA> line 22.
BUG in find_stowed_path? Absolute/relative mismatch between Stow dir .dotfiles and path /home/fattiejb/.local/share/chezmoi/asound/dot_asoundrc_pulse at /usr/share/perl5/vendor_perl/Stow.pm line 966, <DATA> line 22.
BUG in find_stowed_path? Absolute/relative mismatch between Stow dir .dotfiles and path /home/fattiejb/.local/share/chezmoi/asound/dot_asoundrc_pulse at /usr/share/perl5/vendor_perl/Stow.pm line 966, <DATA> line 22.
BUG in find_stowed_path? Absolute/relative mismatch between Stow dir .dotfiles and path /home/fattiejb/.local/share/chezmoi/asound/dot_asoundrc_pulse at /usr/share/perl5/vendor_perl/Stow.pm line 966, <DATA> line 22.
WARNING! unstowing .x would cause conflicts:
  * existing target is neither a link nor a directory: .xinitrc
All operations aborted.
chezmoi: exit status 1

**Comment by szorfein** [comment]
Message with `BUG in find_stowed_path? ...` are annoying but no fatal.  
Here `stow` fail because:
```
WARNING! unstowing .x would cause conflicts:

existing target is neither a link nor a directory: .xinitrc
All operations aborted.
chezmoi: exit status 1
```
So just rename your current `.xinitrc`:

    mv ~/.xinitrc ~/.xinitrc_backup

And restart `chezmoi apply`. 

-> Welcome to Linux :)

**Comment by Jabir-Srj** [comment]
Thanks, it worked!
